backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "img/posts" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blogs" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true
    slug: "pages/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Navigation Title", name: "eleventyNavigation", widget: "object", 
      fields:  
          - { label: "Hide on navbar", name: "parent", widget: "boolean", default: false }
          - { label: "Title on navbar", name: "key", widget: "string", required: false }
          - { label: "Order on navbar", name: "order", widget: "number", default: 0 }
      }
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - { label: "Body", name: "body", widget: "markdown" }

      # - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
      #   name: "eleventyNavigation"
      #   widget: "object"
      #   fields:
      #     - { label: "Hide on navbar", name: "parent", widget: "boolean", default: false }
      #     - { label: "Title on navbar", name: "key", widget: "string", required: false }
      #     - { label: "Order on navbar", name: "order", widget: "number", default: 0 }